env:
  browser: true
  es2022: true
extends: eslint:recommended
parserOptions:
  sourceType: module
rules:
    eqeqeq:
      - warn
      - always
    indent:
      - warn
      - 4
      - 
        ignoredNodes:
            - Program > IfStatement > *
    noControlRegex: off
    noEmpty: off
    sort-imports: warn
    strict: warn
globals:
    browser: readonly
    chrome: readonly
    webext: readonly
    vAPI: readonly
